### ISSUE TITLE
Quick Start in README.md does not refer to the correct path of deploy guide

### ISSUE THREAD

**Issue by JesseStutler** [volcano-sh/volcano-global#4]
### How to reproduce this problem
1. Click the deploy guide ref link in README.md, it redirects to the wrong page:
![image](https://github.com/user-attachments/assets/2087a3d2-8df5-4c06-a625-aecf3e3c2941)
![image](https://github.com/user-attachments/assets/a1e6881d-8aa6-49c0-9336-f5f7f66fe296)

### How to fix this problem
In README, the deploy guide refers to `docs/deploy/README`, which needs to be changed to `docs/deploy/README.md`
![image](https://github.com/user-attachments/assets/5381eeee-e4a6-421a-a1c1-5a2524aeda65)

**Comment by Monokaix** [comment]
/close
fixed by https://github.com/volcano-sh/volcano-global/pull/5
